language: php

php:
 - 5.3.3
 - 5.3
 - 5.4

before_install:
 - cp tests/phpunit.xml.dist tests/phpunit.xml
 - composer install --dev

script:
 - ./vendor/bin/phpunit tests/

notifications:
  email: "widmogrod@gmail.com"